### ISSUE TITLE
Icons bouncing every 2 seconds

### ISSUE THREAD

**Issue by tigglewinks** [friendlyanon/Sajtkukac#1]
Icons bounce horizontally every 2 seconds (I timed it). 
![2019-03-07_16-15-32](https://user-images.githubusercontent.com/25445670/53989704-948d5900-40f4-11e9-849e-f12962ca28ee.gif)

**Comment by friendlyanon** [comment]
Looks like pinned icons are the cause.

I'll investigate further after adding autoupdate.

**Comment by friendlyanon** [comment]
Hello, I cannot reproduce this.  
Can you please walk around the taskbar area with the Inspect.exe tool?  
You can find it here: https://my.mixtape.moe/aaklva.zip  
Or you can find it in the Windows 10 SDK if you don't trust this executable.

You can find an example video here on things of interest: https://streamable.com/dqiqb

**Comment by friendlyanon** [comment]
v0.4 has been released. Are you still experiencing this issue?

**Comment by tigglewinks** [comment]
Working better now. The icons seem to be shifted to the right a little bit (on a 2560x1080 resolution at least). Icons are bouncing less often and it does disable itself entirely occasionally for a few seconds.

Here is an inspect of my taskbar using the UI automation option in the top left: https://pastebin.com/raw/ErsWpErh

Here is an inspect of my taskbar using the MSAA option in the top left: https://pastebin.com/raw/9LreyVLL

**Comment by friendlyanon** [comment]
Thank you for the reply.  
I would prefer a video of you walking thru the tree and showing that to me, with the highlight option enabled as shown in the example video. Preferably with the bouncing happening.

If you don't want to post a link to such a video here you may do so via email [skype1234@waifu.club](mailto:skype1234@waifu.club)

**Comment by taydev** [comment]
I'm currently having the same issue, but the copy of Inspect.exe that you listed earlier (https://my.mixtape.moe/aaklva.zip) is returning a 404. Would you be able to upload a new copy?

My icons are bouncing much more frequently than the two second interval(see gif)
![gif](https://owo.sh/5cWCcgB.gif)

Running on a 1920x1080 display on latest version (v0.4)

**Comment by friendlyanon** [comment]
I have a PC in my possession now that reproduces the issue, I'll make this bug a priority on my list.  
Please don't expect the fix too soon, university is keeping me busy as well.

**Comment by taydev** [comment]
Ah, alright. On an offtopic note, good luck with uni!

**Comment by RLKevin** [comment]
Looks to me like it's bouncing every refresh. With lower refresh rate (higher number) it happens less often.

**Comment by friendlyanon** [comment]
On my test machine I have successfully eliminated the bouncing.  
Please go ahead and test the latest update. If anything occurs out of the ordinary, please report it.
